import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MatchMemo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col px-2 md:px-16 md:py-2 md:m-auto text-textPrimary">
          <Navbar />
          <section className="flex space-x-4 justify-center">
            <Sidebar />
            <div className="flex-grow">{children}</div>
          </section>
        </main>
      </body>
    </html>
  );
}
