import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";
import NextAuthSessionProvider from "@/context/NextAuthSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MatchMemo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col min-h-screen w-full px-3 sm:px-4 md:px-8 lg:px-16 py-2 text-textPrimary">
          <Navbar />
          <NextAuthSessionProvider>
            <section className="flex flex-col md:flex-row gap-4 md:gap-6 md:justify-between flex-1">
              {children}
            </section>
          </NextAuthSessionProvider>
        </main>
      </body>
    </html>
  );
}
